# Pre-modern linguistics

## Introduction

Although linguistics in its contemporary form is a relatively young discipline, language users have certainly been contemplating and studying language much earlier than the formalisation of this domain. Exploring earlier scholarly work on language allows us to understand language users' intuitions and attitudes towards language, and provides alternative perspectives on the nature of language. 

## Eastern traditions of linguistics

It is difficult to pinpoint the exact origin of the study of language. For example, one could argue that the development of a writing system requires some metalinguistic reflection. However, some of the earliest explicit linguistic thought arose in response to language change---when earlier forms of a language (or indeed earlier languages) were deemed significant enough to preserve (e.g., for political, cultural, or religious reasons), language information would be recorded to permit an understanding of older texts employing language forms that were no longer in use.

The oldest written records in this regard come from Mesopotamia, particularly from ancient Babylonia [@graggBabylonianGrammaticalTexts1995]. Around 2000 BCE, Sumerian was declining and being replaced by Akkadian as the language of ordinary use; however, Sumerian remained important as the language of scribal training, as well as the medium for aspects of Mesopotamian culture such as law and religion. Some material was thus collated for use in scribal school; this began with inventories of Sumerian words and their Akkadian equivalents, and later texts demonstrated more organisation into grammatical (e.g., verbal) paradigms. These texts, however, seem to be aide-mémoires rather than comprehensive descriptive grammars; they also seem to concentrate on aspects that were challenging for Akkadian speakers, and that had approximate Akkadian equivalents, reflecting their original purpose [@blackBabylonianGrammaticalTradition1989]. Nonetheless, they demonstrate early thought about morphology and language structure, which is particularly impressive considering that Sumerian was unrelated to Akkadian and had a different morphological alignment (ergative, in contrast with the accusative Akkadian).

In pre-modern India, linguistic analysis arose out of the need to preserve the *Vedas* ('knowledge'), which are Hindu scriptures composed in Vedic Sanskrit around the second millennium BCE. The *Vedas* drove six ancillary branches of knowledge known as the *Vedāṅga* ('limbs of the Veda'), of which four are linguistic in nature: *chandas* (metrics, prosody), *nirukta* (etymology, semantics), *śikṣā* (phonetics), and *vyākaraṇa* (grammar) [@lochtefeldVedanga2002]. The etymology branch initiated the tradition of lexicography [@vogelIndianLexicography1979], beginning with a thesaurus of Vedic terms called *Nighaṇṭu*. The phonetics branch focused on phonetic rules and sound alternations, particularly on the difference between word-by-word recitation (*padapāṭha*) and continuous recitation (*saṃhitāpāṭha*), and also provided classifications of sounds according to articulatory features [@allenPhoneticsAncientIndia1953]. The grammatical branch includes scholarship in the tradition of Pāṇini, whose work *Aṣṭādhyāyī* (fourth century BCE) gave a concise, coherent, and largely complete description of the grammatical structure of Vedic Sanskrit, even including rules relating to regional, stylistic, or sociolinguistic variation [@kiparskyPaninianLinguistics1993]. Later works provided additions, amendments, and commentary [@scharfLinguisticsIndia2013], resulting in a sophisticated body of scholarship that also influenced later linguists, especially as a model of a comprehensive descriptive grammar.

Going further east, Chinese linguistic analysis originated within the field of philosophy, with reflections about the relationship between *míng* ('name', 'word') and *shì* ('actuality'); for example, Confucius advocated for the "rectification of names" to maintain social order [@confuciusAnalects], and Mozi suggested that names should correspond to an actual referent [@moziMoJing]. Later, the emperor of the Qin Dynasty (221--206 BCE) enforced the standardisation of writing and the destruction of classical books, resulting in loss of understanding of ancient texts. When these were rediscovered in the subsequent Han Dynasty (205 BCE--220 CE), philology emerged as a field seeking to ensure accurate understanding of such classical texts. This resulted in works such as *Éryǎ* ("Approaching the Proper Language"; third century BCE), a lexicographic work containing synonyms arranged in semantic categories, and *Shuōwén Jiězì* ('discussing writing and explaining characters'; second century CE), containing descriptions and examples of Chinese character composition principles [@zhuLanguageLinguisticsPremodern2017]. The Chinese linguistic tradition was also influential in other parts of ancient East Asia, and this philosophical--philological tradition continued into later periods of Chinese history.

## Classical traditions of linguistics

Philology and philosophy were also intertwined in the Greek grammatical tradition. One strand of thought arose from the study of language as the medium of expressing knowledge, perceptions, and concepts. Thus, Greek philosophers discussed issues such as the relationship between language and thought, and the origin of language; in particular, the latter relates to the debate about whether the form and meaning of words were connected by nature (*phusis*) or purely by convention (*nomos* or *sunthēkē*), and a major work about this discussion is Plato's *Cratylus* (c. 385 BCE) [@josephLimitingArbitraryLinguistic2000]. Both Plato and Aristotle were also concerned with the relationship between language and reality; this resulted in investigations into meaning and language. Another strand arose from pedagogy: descriptions of Homeric and Attic Greek were necessary in order to ensure the correct performance and interpretation of scholastic literature [@allanWesternClassicalTradition2009]. An important scholar in this tradition is the Alexandrian grammarian Dionysius Thrax, whose work *Technē Grammatikē* ("The Art of Grammar"; c. 200 BCE) established the notion of word classes [@dejongeGrammarRhetoricDionysius2008]. These works, along with others exploring etymology, rhetoric, and poetics, contributed to scholarship around the Greek language, and of language itself.

Roman linguistics continued investigations on similar themes, adopting Greek ideas for use with Latin. For example, Aelius Donatus further developed the notion of the word class and applied it to classical Latin literature in *Ars Minor* (c. 350 CE) [@corneliusGrammarsRhetorics2017]. Priscian later addressed classical Latin syntax in his eighteen-volume *Institutiones Grammaticae* ("Institutes of Grammar"; sixth century CE), based on earlier works of Aelius Herodian and Apollonius Dyscolus [@moranLatinGrammarCrossing2022]. This also became an important pedagogical source for prescriptive Latin grammars, which is significant as Latin remained the language of education and academia for centuries to come.

## Western traditions of linguistics

Subsequent Western linguistic thought largely focused on Latin grammar, as its use as the ecclesiastical and scholarly language persisted even after the dissolution of the Roman Empire in the fifth century. However, Greek scholarship was largely lost to the Western world, and it was only recovered around the twelfth century through the Arabic tradition, resulting in a return to dialectics as a mode of academic thought. A group of mediaeval scholars known as the *modistae* or speculative grammarians adopted some of Aristotle's ideas, such as the idea that all humans have the same experiences of the world, and thus mental experiences [@aristotleInterpretatione]. As such, what is signified in language is universal, and what differs among languages is the means of signifying, or the *modi significandi*. Since these scholars also believed that language was a *speculum* 'mirror, image' that reflects the world, they further suggested that there is a 'universal' grammar common to all languages [@thomasoferfurtModisSignificandiSeu].

A contemporaneous direction was in pedagogy: as grammar was an essential component of university education, a number of pedagogical grammars were composed during this period, including Alexander of Villa-Dei's *Doctrinale* (1199). This was coupled with the increasing use of vernaculars in literature, resulting in the creation of vernacular-medium grammars modelled after the format and content of existing Latin grammars [@swiggersPremieresGrammairesVernaculaires1987]. These include vernacular-medium grammars of Latin, such as Ælfric's *Excerptiones de Prisciano* (in Old English; c. 1000 CE), which may have been useful to students without existing competence in Latin. There were also vernacular-medium grammars of the vernacular, such as the Old Icelandic *First Grammatical Treatise* (c. 1150 CE), demonstrating the emergence of formal thought about languages other than Latin, Greek, or Hebrew [@haydenLanguageLinguisticsMedieval2017].

Renaissance humanism in the fourteenth to sixteenth century prompted a revival of interest in classical antiquity, thereby bringing classical thought about language to the fore again. This was coupled with burgeoning exploration of the world outside Europe, and a concomitant impulse to collect and analyse empirical data. This resulted in an expansion of European linguistic awareness, and a rapid growth in the number of European descriptions of non-European languages [@lawRenaissanceDiscoveryOuter2003]. The arrival of the printing press also resulted in a revolution in means for information transfer, but also prompted linguistic development such as orthographic standardisation [@eisensteinPrintingPressAgent1980]. The emergence of science as a discipline and the broadening of linguistic data thus served as important foundations for the advent of the modern discipline of linguistics.

## Conclusion

The histories of academic disciplines are often presented as a linear, evolutionary narrative. However, this is a misleading characterisation, and histories are more often convoluted and multidirectional. This is certainly the case for linguistics---for example, limited information transfer in the ancient world meant that Eastern linguistic traditions remained much more sophisticated than their Western counterparts for many centuries, although it was the Western tradition that eventually gave rise to modern linguistics. A nuanced and multifaceted approach is thus necessary to understand how ideas about language and linguistics vary across time, space, and schools of thought.
