# The historical turn

## Introduction

Before the eighteenth century, much work on language was normative in nature---for example, there was an emphasis on the study of the "Three Holy Languages", namely Hebrew, Latin, and Greek. There was also a lack of a consistent and systematic approach to language study, and philosophical speculation was often included in scholarly work.

An important shift in paradigm came with Francis Bacon, who introduced the scientific method, suggesting that scholarly inquiry should be grounded in practical empiricism [@baconNovumOrganum1620]. While he did not himself undertake such study, this pronouncement influenced subsequent scholars, such as Gottfried Leibniz, who (among other scholars of his time) proceeded to assemble large-scale word collections to permit language comparison [@leibnizCollectaneaEtymologica1717]. He also shifted the focus from historical language forms to contemporary forms, which are most accessible and comprehensively documentable [@leibnizBrevisDesignatioMeditationum1710]. Leibniz also contributed the notion of genealogical relationship of languages, and suggested that these have to be elucidated by comparing all aspects of languages (i.e., not just the lexicons) [@jankowskyComparativeHistoricalTypological2013]. Like Bacon, Leibniz himself did not study language in his own scholarly work, but his theoretical framework paved the way for the emergence of historical and comparative linguistics.

## The nascence of modern linguistics

One motivating factor contributing to the emergence of linguistics was the growth of knowledge on Sanskrit due to the British colonisation of India. This provided a new source of data, but also generated interest in the topic of languages. A historically esteemed figure in this period is Sir William Jones, who went to the South Asian subcontinent as a judge, but became an important philologist, and advanced the scholarly landscape there by founding the Asiatic Society of Bengal, an organisation designed to further research regarding the East. Jones was already well-versed in Persian and the classical languages, and while seeking to understand local culture, he learned Sanskrit and compared it to Greek and Latin, noting that it bears "to both of them a stronger affinity … than could possibly have been produced by accident" [@jonesThirdAnniversaryDiscourse1807]. It is important to note that Jones' observation isn't original---@campbellHistoryLinguisticsApproaches2017 lists a number of scholars who had presented the concept of Indo-European before Jones. Furthermore, Jones provided no linguistic evidence either. Nonetheless, Jones lent it the influence and authority needed to bring recognition to this hypothesis, and it encouraged other scholars to engage in similar linguistic comparison. It should also be noted that Jones himself retained some legacy notions about the subjective quality of a language (e.g., describing Sanskrit as having a "wonderful structure" and being "more exquisitely refined" than either Latin or Greek), and believed that language data is related to the history and taxonomy of nations and races (which in fact led to his misclassification of both Indo-European and non-Indo-European languages). These ideas persisted into the early twentieth century, although scholars were already dismantling such ideas in the nineteenth century.

Examples of such scholars include Schlegel, who demonstrated the genealogy of relationships by comparing both words and grammatical forms, emphasising the need for procedures as rigorous as those in the natural sciences [@schlegelUberSpracheUnd1808]. He suggested that similarity in words may be due to mutual borrowing, and instead that grammatical similarity was the crux in determining relatedness, by analogy of the elucidation of evolutionary relationship through comparative anatomy. Importantly, he stated that linguistic data should be separated from historical and cultural facts, thereby focusing linguistic study on solely linguistic material. However, Schlegel preserved normative conceptions of language, considering inflected language to be 'organic' and 'superior'.

In contrast, von Humboldt recognised that various linguistic characteristics "do not decide the pre-eminence of languages to one another" [@vonhumboldtUberVerschiedenheitMenschlichen1836]. Von Humboldt also helped construct various epistemological and methodological bases that persist in contemporary historical linguistics. Part of his legacy is his explication of the fundamental principles behind the comparative method [@vonhumboldtEssayBestMeans1830] with an emphasis on empirical data, as well as his astute observation that language is continuously changing and morphing with "never a moment of true standstill" [@vonhumboldtUberVerschiedenheitMenschlichen1836]. His use of a large amount of linguistic material from multifarious languages (including Basque, Chinese, indigenous languages of the Americas, and Polynesian languages, among others) was particularly important in extracting methods that were not confined to Indo-European languages, but which could apply to data from any family of languages.

This emphasis on a data-driven approach was picked up by other scholars of the time, including Bopp, whose first major work *Konjugationssystem* [@boppUberKonjugationssystemSanskritsprache1816] was an extensive comparison of Indo-European languages intended to "put an end to all by-chance matters" and securely establish a valid model of the relationships within this language family. Grimm also emphasised an empirical approach, and himself accumulated large amounts of philological data, leading to his description of the Germanic consonantal shift now known as Grimm's law (voiced aspirated stop > voiced stop > voiceless stop > voiceless fricative) [@grimmDeutscheGrammatik1819]. Again, this correspondence is not original (having at least been noticed by Rask [@raskUndersogelseOmDet1818]); nonetheless, Grimm's work was accompanied by extensive textual documentation and provided a formal description for the phenomenon. Together, the work of these early scholars described a coherent methodology for historical linguistics.

## The development of historical linguistics

From the middle of the century onwards, linguistics began to expand as a discipline, with various scholars contributing grammars and comparative analyses of many different languages, including those of Africa, Asia, and the Pacific islands. This period introduced novel formal conventions for working in historical linguistics. On one hand, there was an increasing emphasis on the use of phonetic descriptions in understanding sound change, in contrast with earlier work, which was primarily phonological or even orthographic. This was advocated by historical linguisticians who were also adept phoneticians, such as @sieversGrundzugeLautphysiologieZur1876.

On another hand, Schleicher introduced innovations for representing the theories that arose in historical linguistics, including the Stammbaum or family-tree model of language descent [@schleicherCompendiumVergleichendenGrammatik1861]---which is still used to identify and represent genealogical relationships, even if the model has since been superseded. He also introduced the use of reconstructed proto-language forms as a basis for establishing relationships between languages, along with the convention of using an asterisk to indicate reconstructed items. This research direction contrasted with prevailing views that Sanskrit was the source of all Indo-European languages due to the antiquity of its materials; instead, Grassmann found that Germanic was "older" in one phonological pattern than Sanskrit was [@lehmannReaderNineteenthCentury1967], and work by both Grassmann and Schleicher established the empirical and explanatory need for the positing of proto-languages. It is interesting to note that Schleicher's innovations arose by analogy of work from evolutionary biology; indeed, he believed that languages behave like natural organisms, evolving without the conscious input of their users, and hence was amenable to the same analyses used in the natural sciences [@schleicherDarwinscheTheorieUnd1863].

Another ideological contribution of Schleicher's is an insistence that sound laws be as regular as possible, foreshadowing the work of the Neogrammarians [@schleicherCompendiumVergleichendenGrammatik1861]. This idea was expressed in the work of scholars who contributed further refinements in the analysis of sound correspondence data. This includes Grassmann [@grassmannUberAspiratenUnd1863], who found that some Sanskrit forms had undergone dissimilation of two aspirated stops in adjacent syllables, with the first losing its aspiration; this explained some correspondences with their Germanic cognates that were previously considered exceptions to Grimm's law. Ascoli [@ascoliLezioniDiFonologia1870] similarly suggested that Proto-Indo-European had both velars and labiovelars, which could explain differences in correspondences with Greek stops. These developments hint at increasing thought about the nature of language change, rather than merely its description, and also demonstrated a tendency towards increasing precision in describing and theorising about language data.

## The Neogrammarians

At the end of the century, a new school of historical linguisticians arose both in reaction to and in culmination of the previous decades of work in the discipline; these were the *Junggrammatiker*, or the Neogrammarians. This school is defined by the principles with which they approached historical linguistics: that language does not have a speaker-independent reality, and that the human factors affecting language are constant (the uniformitarian principle). These resulted in a number of methodological principles as well: that sound change occurs without exception (the regularity principle), and that analogy is an important mechanism of language change. Such principles were definitively articulated in what is often known as the "Neogrammarian Manifesto" [@osthoffVorwort1878]. These principles were controversial as they were in opposition to some of the ideas of earlier scholars (e.g., Schleicher's suggestion that language development occurred in two distinct stages of language formation and language decay), but arose out of a desire to remedy the imprecision of earlier descriptions of linguistic relationships, and to render the discipline as rigorous as the natural sciences. Furthermore, the positing of exceptionless sound laws is necessary to give the comparative method an adequate theoretical basis, since this mitigates the need to determine how 'similar' forms need to be to be considered related (since it is systematicity that is more important) [@harrisonLimitsComparativeMethod2003].

Central to their efforts were attempts to account for all instances of phonological change, including both phonemic and suprasegmental phenomena. To this end, Karl Verner (who was only loosely associated to the group) played an important role: he demonstrated that a large swathe of residues from Grimm's law could be accounted for by positing the voicing of voiceless fricatives immediately following an unstressed syllable in Proto-Germanic (now known as Verner's law) [@vernerAusnahmeErstenLautverschiebung1875], thereby encouraging the Neogrammarians to pursue a total accounting of the phonological data. This demand for accounts of data that are as accurate as possible has certainly persisted as a methodological ideal in the field of linguistics.

Much subsequent work has investigated the validity of the Neogrammarian hypothesis, and while this topic more appropriately belongs in historical linguistics itself, one point worth mentioning is that the Neogrammarian "sound change" refers exclusively to a particular type of phonetic change (i.e., that is completely regular and lexically abrupt), and indeed they attribute many apparent counterexamples to other language change processes, namely borrowing and analogy [@chenSoundChangeActuation1975]. Thus, part of the Neogrammarians' work was to determine which particular process best described an instance of language change, and this also became an important aspect of the comparative method (i.e., deeming whether words are cognate or merely borrowed).

Another theoretical direction is the psychologism introduced by Hermann Paul [-@paulPrincipienSprachgeschichte1880], suggesting that language must be understood as a mental process. This perspective allowed variation across both space and time to be explained as variation in speakers' production and in listeners' interpretation, thereby constructing a single theory that incorporates social, psychological, and physiological factors to explain why languages change at all. It also explains the Neogrammarians' focus on the idiolect (rather than an abstract language system) as the primary object of linguistic investigation. The Neogrammarians were thus a source of many theoretical innovations that drove newer fields of research, even if some of their hypotheses were later refuted or superseded.

## Conclusion

The eighteenth century was a foundational period for linguistics, with a focus on the historical aspects of linguistic study. It helped to identify language as a possible target of scientific study, and prompted thought on data gathering, analytic techniques, and formal descriptions. These themes would remain essential in practically all subsequent work on language. This period was also the source of ideas about language change and the relationship between languages, which remain important in the field of historical linguistics to this day.
