# European structuralism

## Introduction

Linguistic thought in the nineteenth century was dominated by a historical focus, which led to increasingly sophisticated descriptions of language change. However, there had not been coherent conceptions of "language" itself. The prevailing positivism also meant that scholarship often adopted an atomistic perspective---i.e., the idea that only individual facts are relevant objects of study. Instead, the structuralist school argued that the *relationships* between these should be studied [@albrechtEuropeanStructuralism2011]. Within the realm of linguistics, this movement suggested that language can be analysed as a well-structured system, and elucidating the nature of that system became the focus of the European structuralists of the early twentieth century.

## Ferdinand de Saussure

It is undeniable that de Saussure is a major figure involved in the emergence of the structuralist movement. Interestingly, his earlier work was rather Neogrammarian in nature [e.g., he published a book on the Indo-European vowel system in 1878\; @desaussureMemoireSystemePrimitif1878]. Later, however, he became less certain of those ideas, and this change was reflected in a declining frequency of publication. During this period, he sought to characterise linguistic study and its aims, and these ideas entered into three courses in general linguistics that he gave at the University of Geneva. The material from these courses was consolidated by two former students, Bally and Sechehaye (who had not actually attended these courses themselves), and this was eventually published as the *Cours de Linguistique Générale* [@desaussureCoursLinguistiqueGenerale1916], which laid the foundational work for structural linguistics.

In *Cours*, de Saussure presented several key dichotomies on topics including the approach of linguistics, the object of linguistic study, and linguistic semiotics. The first distinction is that between synchronic linguistics, concerned with the state of a language at one particular point in time, and diachronic linguistics, concerned with the change in one particular aspect of a language over time. Unlike his predecessors, de Saussure suggested that synchronic linguistics should be primary, as language users do not need to know the diachrony of their language in order to use it. The opposition between these two axes can be summarised as follows: "synchronic facts are systematic and meaningful; diachronic facts are isolated and ateleological (i.e., without a goal)" [@graffiEuropeanLinguisticsSaussure2013].

Another distinction is that between *langue*, the total system of a language across the language community, and *parole*, the execution of language by an individual via acts of speech. To de Saussure, language was primarily a "social fact" (rather than a psychological one), and linguistic study should aim to describe *langue* by studying *parole*, which reflects and represents the *langue* of the society that the individual belongs to. De Saussure also distinguished these two from *langage*, or the human faculty of language, which contributes to both *langue* and *parole* but is distinct in its psychological nature.

De Saussure also contributed to linguistic semiotics by distinguishing between the *signifiant*, the form of a sign (the sound-image of a sign), and the *signifié*, the concept designated by a sign. He further suggested that the relationship between the two is arbitrary (i.e., without logical connection) as opposed to motivated (i.e., with resemblance between *signifiant* and *signifié*). It is important to note that de Saussure's conception of this relationship relates not primarily to the relationship between language and reality (which had been commented on before), but a relationship internal to language. That is, the *signifié* is not a real object, but rather an abstract concept embedded in a language.

Language, then, comprises a number of signs that are delineated in opposition to one another within the system of a language. The relations between signs can be analysed in the syntagmatic dimension (i.e., relationships between a sign and the signs before and after it) and in the paradigmatic dimension (i.e., relationships between a sign and other alternative signs that could have filled its location in the syntagm); thus, the meaning of a word is constructed by the oppositions between a word and other words in its syntagm and paradigm. De Saussure captured this notion by comparing language to chess, suggesting that in both systems, units were valued in relation to other units. This idea is the "structure" referred to in structuralism, and reflects a core ideology that anchored this movement, despite the considerable differences both among and within the various schools of European structuralism that emerged after de Saussure.

## The Geneva School: Return to psychologism

It has sometimes been claimed that much of the material in the *Cours* is in fact based on the ideas of its editors, Bally and Sechehaye, who brought the book together by referencing the notes taken by students who had attended de Saussure's lectures [@englerMakingCoursLinguistique2004]. Regardless of the veracity of this claim, it is clear that scholarly work by both editors demonstrated key differences in their philosophies of language as compared with de Saussure, particularly in their adoption of a mentalistic view of language. It is seemingly paradoxical that the scholars who were closest to de Saussure should have experienced the least influence from him; this observation, however, can be resolved by noting that Bally and Sechehaye had already developed their own viewpoints before de Saussure had delivered his lectures, explaining the divergence in thought [@graffiEuropeanLinguisticsSaussure2013].

This is evident in Sechehaye's first book, which appeared before the *Cours* in 1908 [@sechehayeProgrammeMethodesLinguistique1908]. In it, he suggested that the primary issue in theoretical linguistics involved the "grammatical problem", referring to the "psychophysical basis" of grammar. Later, he also disagreed with de Saussure's conception of *langue*, suggesting instead that language does not exist as an entity over and above individuals' language [@sechehayePenseeLangueOu1933].

Bally focused on a different issue, concerning the "intellectual" and "affective" components of language---the former refers to the content of an utterance, while the latter refers to additional information regarding the speaker's emotions, intentions, and so on, which are inevitably transmitted during actual conversations due to the communicative, dialogical nature of language use [@ballyLexpressionIdeesSphere1926]. He went on to study the effects of both components, a discipline which he termed "stylistics". Some of Bally's other ideas, however, do seem to be inspired by de Saussure, including his suggestion that *parole* is the actualisation of *langue* [@ballyLinguistiqueGeneraleLinguistique1932].

## The Prague School: Functionalism and phonology

Some of the Genevans' focus on the communicative functions of language can also be seen in the Prague school. For example, Mathesius developed a framework for sentence analysis distinguishing between a "grammatical analysis", which subdivides a sentence into the traditional subject and predicate, and an "actual analysis", which subdivides a sentence into theme and rheme [@mathesiusLingvistickaCharakteristikaJeji1929]. These two analyses are both essential and may not coincide. This perspective, while not particularly popular in the early twentieth century, went on to inform the later school of structural functionalism.

Mathesius was also important for his organisational work---he founded the Prague Linguistic Circle in 1926, bringing together influential European structuralists, including the Russian linguisticians Trubetzkoy and Jakobson. A significant contribution of this group is its "1929 Theses" [@brunoThesesPresenteesAu1929], which expressed their conception of language and linguistic study. Particular theses worth highlighting include the first thesis, which opposed de Saussure's sharp division between synchrony and diachrony, and instead suggested that particular stages of a language still contain traces of earlier stages. Jakobson later picked this idea up in the field of historical phonology [@jakobsonPrinzipienHistorischenPhonologie1975], which looked at systematic sound changes over time, and he was also interested in how children's phonological acquisition could also reflect cross-linguistic phonological histories [@jakobsonChildLanguageAphasia1968]. The third thesis reflected Mathesius' functional view of language, suggesting that different linguistic functions (e.g., communicative, referential, poetic) must be considered in an adequate account of language; this theme was also revisited by Jakobson in his later work [@jakobsonLinguisticsPoetics1960].

A thesis that came to shape much of the Prague school's scholarly work is the second thesis, distinguishing between sound as "an objective physical fact" and as "an element of a functional system"; this notion was foundational in the emerging field of phonology. Trubetzkoy distinguished between phonetics, which he defined as the science of sounds "pertaining to the acts of speech", and phonology, the science of sounds "pertaining to the system of language" [@trubetzkoyGrundzugePhonologie1939]. Thus, the former studies the acoustic and articulatory properties of linguistic sounds, while the latter studies linguistic sounds in terms of their "distinctive functions" (i.e., position within a paradigm). This leads naturally to the now-familiar notion of the phoneme, the basic mental unit of sound whereby the substitution of one for another creates a minimal pair; in Trubetzkoy's words, "the primary object of phonological study is, in fact, the types of sound opposition that can create distinctions in meaning" [@trubetzkoyStudiesGeneralLinguistics2001].

Jakobson further developed some of Trubetzkoy's ideas on the contrasts between phonemes, suggesting the concept of the distinctive feature---i.e., particular characteristics of a phoneme whereby substitution of one feature results in a different phoneme, and suggested that these are binary in nature [@jakobsonFundamentalsLanguage1956]. He also proposed specific features such as "lightness/darkness" (i.e., frontness/backness), "chromatism" (i.e., openness/closeness), and oral/nasal. Thus, the phoneme can be reformulated as "a bundle of distinctive features", providing a framework for a systematic organisation of phonemes, rather than an unsystematic "stamp-collecting" approach to cataloguing the sounds used in various languages.

## The Copenhagen School: Further semiotics

Unlike the Prague school, the Copenhagen Linguistic Circle did not share a common theoretical perspective. Arguably the most significant figure of this school is Hjelmslev, who further developed a framework for semiotics by extending Saussure's sign model [@hjelmslevProlegomenaTheoryLanguage1953]. He renamed the Saussurean *signifiant* and *signifié* as the expression plane and the substance plane respectively, and further distinguished between form (language-internal aspects of language) and substance (extrinsic aspects of language). In his view, expression-substance (articulable sounds) and content-substance (concepts) are ancillary, but should not be the focus of linguistic study. Instead, he proposes that the relationships between expression-forms and content-forms should be the object of linguistics, and thus developed the methodology of glossematics (with a glosseme being the smallest unit of both expression-form and content-form). While this approach did not gain much traction in linguistics, it remains a cornerstone of modern semiotics.

## The London School: Studying *parole*

The loosely-termed "London school" typically refers to Firth and his students, who, while having been influenced by de Saussure and continental structuralism, developed their own framework in the study of language. For example, Firth's own work aimed at analysing language in terms of its embodied use in particular situations, rather than an abstract supra-individual language structure. He suggested that meaning could not be understood independently of the situational context and the linguistic collocation (or co-text), thereby emphasising the syntagmatic dimension of relations [@firthModesMeaning1958]. These ideas served as a precursor to later work in semantics and pragmatics.

## Conclusion

The twentieth century was a pivotal period for linguistics, containing some of the earliest formulations of the concept of "language" itself. The Saussurean idea of language as system was implemented in many different ways by the different European schools of structuralism, but to encapsulate the essence of European structuralism, we return to de Saussure, who reiterates that "the linguist[ician] must take the study of linguistic structure as his primary concern" [@desaussureCoursLinguistiqueGenerale1916]. In that regard, arguably all of subsequent linguistics is structuralist in nature, since the scientific study of language presupposes that it is ordered rather than random, demonstrating the far-reaching effects of de Saussure's fundamental contributions.
