# American structuralism

## Introduction

American linguistics began in earnest around the twentieth century, spearheaded by scholars who were influenced by the then-flourishing European structuralism. While American structuralists maintained some of the traditions of their European counterparts, such as the emphases on synchrony and systematicity [@josephHowStructuralistWas1999], they also contributed to linguistic thought in two key ways, namely a focus on data-driven linguistics, and a refinement of analytical tools. These helped to establish important concepts and methodologies that influenced subsequent schools of linguistic thought, and still play a role in modern linguistic understanding.

## Linguistics as anthropology

Early American structuralist thought considered linguistics to be an offshoot of anthropology. Many early American linguisticians including Boas, Sapir, and Whorf were also involved in anthropology, and much of their work was driven by a desire to describe Native American languages, which were facing possible extinction [@hymesAmericanStructuralism1981]; indeed, Boas' descriptions of some now-extinct Native American languages were the last (and sometimes the only) significant sources of data on them [@campbellHistoryLinguisticsApproaches2017]. This research led to discourse about how language relates to ethnography, and introduced perspectives from anthropology such as an emphasis on the equal worth of all cultures and languages [@boasIntroduction1911], thereby refuting earlier "evolutionary" views of language [which purported that the morphological type of a language reflected the stage of social evolution of its associated society\; @schleicherCompendiumVergleichendenGrammatik1861].

An alternative interpretation, also arising from concurrent anthropological and linguistic work, is that language and culture may be related; this has led to the development of the Whorfian hypothesis [@whorfLanguageThoughtReality1956], which suggests that a language determines its speakers' thoughts and cognitive categories. This hypothesis has aroused significant interest and research into the topic, and resulted in interdisciplinary efforts in linguistics, anthropology, and psychology; most current evidence seems to suggest that the strong form of the hypothesis is false, but that language does influence thought in certain (more minor) ways [see e.g., @danesiLinguisticRelativityToday2021; @gentnerLanguageMindAdvances2003; @huntWhorfianHypothesisCognitive1991; @khishigsurenComputationalAnalysisLexical2025; @niemeierEvidenceLinguisticRelativity2000].

## Phonetics and phonology: A methodological overhaul

The drive to describe each language on its own terms resulted in dramatic changes in the approach to data collection; this shift was particularly apparent in the domain of phonetics and phonology. Traditional descriptions often carried Eurocentric biases, and earlier linguisticians had perceived more "primitive languages" to have less accurate pronunciations. Instead, Boas demonstrated that this phenomenon was due to effects of "perception through the medium of a foreign system of phonetics" [@boasIntroduction1911], particularly due to the fact that the phonetic inventories of different languages vary significantly, and may not use the same category boundaries. This reflects Boas' anthropological perspective, and was important in challenging linguisticians to create more accurate descriptions of other languages' phonologies.

An appreciation of this non-isomorphic relationship between physical sounds and linguistically relevant sound categories also led to further characterisations of the distinction between phonetics and phonology. For example, Sapir emphasised that "sounds and sound processes of speech cannot be properly understood in such simple, mechanical terms" [@sapirSoundPatternsLanguage1925]. He proposed that non-speech oral sounds (such as blowing out a candle) may require similar gestures to produce and may be acoustically similar to actual speech sounds, but the two are distinct in several ways. The former are functional while the latter have no direct functional value; each act of blowing out a candle is functionally equivalent while speech sounds have no unifying reference; no variation in blowing extends over into a substantially different class of actions; and most importantly, speech sounds can be placed into a system.

The notion of a phonemic system thus developed in parallel with the work of European structuralists such as Trubetzkoy and Jakobson. In particular, @chaoNonuniquenessPhonemicSolutions1934 defined the phoneme as a class of sounds (i.e., phones, or even instantiations of phones) in a language, such that they are distinctive---on one hand, words that are considered to have different pronunciations differ either in the order or in the constituency of such classes, and on the other hand, only the relevant features are specified, while other irrelevant features are unspecified (e.g., whether [t] is dental or alveolar). As such, he emphasised the importance of the distinction between phonetic (narrow) transcription and phonemic (broad) transcription---the former includes all phonetic detail, even if they have no bearing on distinctiveness of words, while the latter only refers to features that are relevant in distinguishing words. These ideas helped to pave the way for accurate phonemic descriptions of non-Indo-European languages, with particular care given to non-egocentrism (that the linguistician did not use their prior conceptions or assumptions about phonemic systems to describe a different language); indeed, much of the lasting impact of the American structuralists comprises the quantity and quality of the language data they collected, leading some to call them "American descriptivists" instead [e.g., @blevinsAmericanDescriptivismStructuralism2013].

## Grammar: The representational turn

Another consequence of the view that language is part of culture is the characterisation of language as having a primarily communicative function. This approach resulted in a focus on sentence-level morphosyntax, as explained by Boas: "Since all speech is intended to serve for the communication of ideas, the natural unit of expression is the sentence" [@boasIntroduction1911]. For example, @harrisMorphemeUtterance1946 described a method to formally construct utterances as sequences of morphemes using an operation he terms "substitution"---that is, the replacement of morphemes or sequences of morphemes with other sequences that belong to the same class (e.g., the replacement of a noun with a determiner-adjective-noun sequence). This provided a "compact description of the structure of utterances in the given language" [@harrisMorphemeUtterance1946] in the form of equations that resemble modern phrase structure rules (e.g., "A + N = N"), and provided a technique to compare the syntactic structures of different languages in a formal manner---for example, Harris compares the grammars of English and Hidatsa. @wellsImmediateConstituents1947 further extended this notion by describing a method of deriving these "immediate constituents" from utterances (i.e., an analytic approach, rather than Harris' synthetic one). Finding successive layers of immediate constituents and describing their relationship thus became the focus of syntactic analysis [@gleasonIntroductionDescriptiveLinguistics1955], providing a robust and systematic approach to understanding syntax that was not modelled after familiar or "superior" languages such as Latin or Greek.

Extrapolating the difference between items and arrangements, @bloomfieldLanguage1933 distinguished between lexical form and grammatical arrangement, reiterating the primacy of the sentence. He further described a novel conceptual system that would encompass phonology, morphosyntax, and even some aspects of semantics and pragmatics:

  | | | Lexical | Grammatical |
  |----|----|---------|-------------|
  | Smallest unit of linguistic signalling | Pheneme | Phoneme | Taxeme |
  | Smallest meaningful unit | Glosseme | Morpheme | Tagmeme |
  | Meaning of unit | Noeme | Sememe | Episememe |

Bloomfield's model was critical in suggesting that grammatical processes such as selection and ordering can be meaningful---that is, choosing one construction (e.g., an imperative) over another (e.g., a declarative) conveys meaning (episememe) above and beyond the lexical meaning of the components (sememe) in the sentence. This approach was furthered by his student Pike into the field of tagmemics [@pikeLanguageRelationUnified1967], which considered how hierarchical linguistic structures (e.g., morpheme > word > phrase > sentence > paragraph > discourse) could be understood in terms of the tagmemes of different levels of organisation. It should be noted that Bloomfield and Pike had slightly different conceptions despite using similar terms [@blevinsAmericanDescriptivismStructuralism2013], and although this method was not generally adopted subsequently, there are echoes of a similar emphasis on arrangement patterns in later construction grammar approaches [@lakoffLinguisticGestalts1977]. This also demonstrates the American structuralists' shift in focus from studying the properties of languages to the properties of the analytical devices themselves [@blevinsAmericanDescriptivismStructuralism2013].

## Behaviourism

Within the field of psychology, earlier psychodynamic theories emphasised the role of (conscious or unconscious) mental processes, which were often unable to generate empirically testable hypotheses. This failure led to the opposing school of behaviourism, spearheaded by scholars such as Skinner and Bloomfield, which focused on measuring and explaining observable behaviour. Specifically, behaviourism suggested that all behaviour could be understood as responses to stimuli, modulated by prior reinforcement and punishment events in the individual's history.

In the field of linguistics, behaviourists considered language to be a type of human behaviour, which was thus explainable using behaviourist concepts of conditioning and stimulus--response sequences [@skinnerVerbalBehavior1957]. In particular, Bloomfield suggested that "language enables one person to make a reaction … when another person has the stimulus" [@bloomfieldLanguage1933]. He proposed that language is employed when one person receives a stimulus, and produces a speech (or substitute) re-action, which then serves as a speech (or substitute) stimulus for another person, resulting in a reaction [@bloomfieldLanguage1933; @bloomfieldSetPostulatesScience1926]. Bloomfield illustrated this with an example: If Jill sees an apple in a tree and is hungry, she may make an utterance to Jack, which would cause him to climb up the tree and retrieve the apple for Jill, who can then eat it. As such, Bloomfield suggested that speech is "only a way of getting one's fellow-men to help … worthless in itself, but a means to great ends" [@bloomfieldLanguage1933]; this demonstrates Bloomfield's notion that language is fundamentally social in character [@ryckmanGrammarInformationInvestigation1986]. Bloomfield further suggested that language could be understood mechanistically---that is, given a particular stimulus and the life history of an individual, the response (including speech reactions) is determinable, and that variability in possible responses "is due only to the fact that the human body is a very complex system "[@bloomfieldLanguage1933].

This conceptualisation of language is also related to theories of language acquisition. Bloomfield suggested that language behaviour arises from a process of habit development. Children's speech begins with (approximate) imitation, which becomes increasingly like adult speech through reinforcement of correct utterances (e.g., receiving a doll after uttering "doll" correctly) and punishment of incorrect utterances (e.g., ignored requests) [@bloomfieldLanguage1933]. Such reinforcement and punishment change the strengths of various verbal responses, until children's speech becomes fully perfected.

Significantly, the behaviourist framework influenced their perceptions of the aim of linguistic theory. Bloomfield suggested that studying language involves studying the "coordination of certain sounds with certain meanings", with meaning referring to "the important things with which the speech-utterance … is connected, namely the practical events [preceding and proceeding from the speech-utterance]" [@bloomfieldLanguage1933]. To Bloomfield, the only possible target of scientific study was observable phenomena, which would include these "practical events" as well as the speech utterance itself; he suggested that it is the speech signal in particular that linguisticians should concern themselves with. This also reflects Bloomfield's structural approach to linguistic research, and his theory that form (phonology) must be considered in relation to meaning (semantics, which for Bloomfield included grammar): "In language, forms cannot be separated from meanings. It would be uninteresting and perhaps not very profitable to study the mere sound of a language without any consideration of meaning" [@bloomfieldMeaning1943]. For Bloomfield, the objective of linguistic theory was thus to characterise the nature (form and meaning) of the speech signal through formal analysis of observable evidence.

It is important to comment on some of the implications of the behaviourist approach. Their acceptance of the anthropological prohibition against generalisation meant that the behaviourists could not evaluate their descriptions against a general theory regarding human language. Simultaneously, their rejection of mentalism implied that they could not evaluate their descriptions against native speakers' mental knowledge about the language. As Campbell notes, this means that "nothing remained except method, 'discovery procedures,' the search for contrast and complementary distribution in the data recorded by linguists" [@campbellHistoryLinguisticsApproaches2017].

## Conclusion

Given the development of behaviourism into methodology without theory, it is not surprising that this framework failed to gain traction in linguistics. Nonetheless, American structuralism's primary impact was in enhancing the rigour of empirical data collection and encouraging reflection on the analytical methods employed. The fact that many of their ideas (e.g., precise phonetic transcription, constituency analyses) are taken for granted in contemporary linguistics demonstrates the extent of their legacy, which continues to influence the way linguisticians observe and process linguistic data.
