# Generativism

## Introduction

It is undeniable that one of the most important figures in modern linguistics is Noam Chomsky. In the middle of the twentieth century, he became a prominent opponent to behaviourist linguistics, and adopted a more mentalist approach, suggesting that mental processes could be a valid object of scientific study. He introduced the school of generativism, which was marked by its commitment to linguistic essentialism, focusing on "abstract universal principles that explain the properties of specific languages" by measuring native speakers' intuitions about language, as well as linguistic nativism, the notion that linguistic capabilities are, to some extent, dependent on structures and processes that are innate to humans, rather than acquired through domain-general learning processes [@scholzPhilosophyLinguistics2024]. These ideologies resulted in a novel and robust framework for conceptualising language and the aim of linguistic study.

## Against behaviourism

The behaviourist framework purported that observable behaviour is the only evidence appropriate for scientific study, and that all behaviour is explainable via the process of conditioning, in which an agent's responses adjust in relation to other events. Thus, under this view, language use occurs solely as a response to particular stimuli, and is purely instrumental in nature. However, Chomsky's [-@chomskyReviewSkinnersVerbal1959] scathing review of Skinner's [-@skinnerVerbalBehavior1957] *Verbal Behavior* dismantled many of the claims of behaviourism, and has even been claimed to be "the single most influential paper published since Watson's Behaviorist manifesto" [@leaheyHistoryPsychologyMain1987], and to have "sounded the death-knell for behaviorism" [@smithChomskyIdeasIdeals1999].

A crucial aspect of Chomsky's review is his criticism of the notions of stimulus and response used in relation to verbal behaviour. He suggested that these are not well-defined, and that a broader definition of these terms ("any physical event to which the organism is capable of reacting" and "any part of behavior" respectively) would result in the relationship between stimulus and response no longer being valid. Indeed, part of the behaviourist argument relies on internal stimuli and automatic self-reinforcement to explain continued speech production, even though these are not directly observable; Chomsky proposed that these may merely be cover terms "for any factor, detectable or not, related to acquisition or maintenance of verbal behavior" [@chomskyReviewSkinnersVerbal1959], thereby questioning the behaviourists' purported restriction of linguistic study to observable behaviour. In contrast, Chomsky considered language to be an abstract object, "a set (finite or infinite) of sentences, each finite in length and constructed out of a finite set of elements" [@chomskySyntacticStructures1957]. This object is describable by a grammar, which can generate all the grammatical sentences of a language. In his view, the observable behaviour of language production is merely a reflection of this abstract object: "Behavior is evidence. It's not what you are studying; what you are studying is competence, capacity" [@virues-ortegaCaseSkinner452006]. This demonstrates his mentalist position, emphasising the mental processes and capacities of an individual that underlie observable language use.

Chomsky's views on the nature of language also explains some of his criticisms on the behaviourist notion of learning. Contrary to the claims of Bloomfield, Chomsky noted that much of children's language acquisition is not accompanied by "careful differential reinforcement" of adults, but merely arises from "casual observation and imitation of adults and other children" [@chomskyAspectsTheorySyntax1965]. These critiques were later supported by empirical work, which showed that parents do not provide positive verbal reinforcement for sentences that are grammatical, but rather reinforce truthful ones [@brownDerivationalComplexityOrder1970; cf. @schonebergerThreeMythsLanguage2010]. If the behaviourist hypothesis were correct, this would make our language behaviour truthful but ungrammatical, which is the opposite of what we find in adult humans. Instead, Chomsky proposed that children have some innate linguistic knowledge which "specifies the form of the grammar of a possible human language", as well as "a strategy for selecting a grammar of the appropriate form that is compatible with the primary linguistic data" [@chomskyAspectsTheorySyntax1965]. This nativism is captured in his comment that "there is surely no reason today for taking seriously a position that attributes a complex human achievement entirely to months (or at most years) of experience, rather than to millions of years of evolution or to principles of neural organization that may be even more deeply grounded in physical law" [@chomskyAspectsTheorySyntax1965].

Contemporary studies in psycholinguistics also provided another source of evidence against the simplistic view of behaviourism. An example is Berko's seminal *wug* test [@berkoChildsLearningEnglish1958], which demonstrated children's ability to generalise morphological rules to novel lexical items (e.g., responding with *wugs* when prompted to provide a plural form for *wug*). This suggested that "the acquisition of language is more than the storing up of rehearsed utterances" [@berkoChildsLearningEnglish1958], demonstrating that humans' language capacity is more robust and flexible than can be accounted for by rigid behaviourist descriptions.

## Understanding generativism

Chomsky's assumptions that language was a mental capacity and infinite in size informed his perspective that the aim of linguistic theory should be the description of grammars that can fully describe individual languages, and language more generally. At the language-specific level, the fact that finite grammars must be used to describe infinite languages suggested that it must employ "recursive devices of some sort" in order to generate the grammatical sentences of the language, giving rise to the generative grammar approach to linguistics [@chomskySyntacticStructures1957].

His characterisation of language as a mental capacity also suggested that it could be affected by various other non-linguistic factors (e.g., attention, memory). As such, Chomsky distinguished between performance theories, which aimed to characterise observed behaviour, and competence theories, which aimed to describe the mental representation of language users' linguistic knowledge [@chomskyCurrentIssuesLinguistic1964]. He employed evidence other than observed utterances, such as linguistic intuitions, attempting to "abstract from the observation a more perfect class of behavior than that presented by any one record" [@pylyshynRoleCompetenceTheories1973]. For Chomsky, performance theories could only aim for observational adequacy (providing an accurate description of observed data), while competence theories could further aim for descriptive adequacy (accounting for linguistic intuition), and are therefore the more appropriate goal for linguistic inquiry. This is related to the distinction between competence ("knowledge of language") and performance ("ability to use that knowledge")—the latter is affected by other performance factors, such as memory and attention, which Chomsky considered irrelevant to language itself [@chomskyKnowledgeLanguageIts1986].

Chomsky later refined his conception of the object of linguistic study by proposing a distinction between I(nternalised)-language and E(xternalised)-language [@chomskyKnowledgeLanguageIts1986]. I-language is "some element of the mind of the person who knows the language", and is intended to be a mnemonic for three characteristics: individual (a property of individual human beings rather than groups), internal (relating to representations in the mind), and intensional (defined by a formal specification) [@chomskyExplainingLanguageUse1992]. This concept contrasts with E-language, which is external (relating to representations outside the mind) and extensional (defined by enumerating the set of permitted strings). Chomsky suggested that E-language is a poor candidate for linguistic study as it is an "artificial, somewhat arbitrary" construct [@chomskyKnowledgeLanguageIts1986], while I-language refers to a real-world object (i.e., an actual state of the mind/brain of a native speaker), and should be the focus of linguistics.

Another key component of the generativist philosophy of language relates to the language acquisition process. Chomsky notes the problem of the "poverty of stimulus"—i.e., that theories of language acquisition have to account for "the richness, complexity, and specificity of shared knowledge, given the limitations of the data available" [@chomskyKnowledgeLanguageIts1986], such as speech errors, incomplete utterances, and the finiteness of actual utterances. In other words, posited acquisition processes must be able to account for the development of robust I-language despite the influence of performance factors on the primary linguistic data received by the acquirer. To account for this, Chomsky proposed a "language acquisition device", which is "an innate component of the human mind that yields a particular language through interaction with presented experience" [@chomskyKnowledgeLanguageIts1986]. 

Combining this with the concept that knowledge of language can be conceived as states of the mind/brain, he suggested that the language faculty can be described as having an innate initial state $S_0$ common to all humans; this then develops through relevant experience into a steady state $S_S$, which is the state of knowing a particular I-language. Chomsky thus introduces universal grammar (UG) as a theory about $S_0$, or a "characterization of the genetically determined language faculty" [@chomskyKnowledgeLanguageIts1986]. Furthermore, since this UG must be able to account for the fact that $S_0$ can develop into many dissimilar I-languages, UG can also be considered as a "framework of principles and element common to attainable human languages" [@chomskyKnowledgeLanguageIts1986]. Thus, Chomsky suggested that the primary objective of linguistic theory is "to develop an account of linguistic universals that, on the one hand, will not be falsified by the actual diversity of languages and, on the other, will be sufficiently rich and explicit to account for the rapidity and uniformity of language learning, and the remarkable complexity and range of the generative grammars that are the product of language learning" [@chomskyAspectsTheorySyntax1965].

## The language bioprogram hypothesis

A related research direction was taken by Bickerton, who sought to understand the underlying language faculty by considering another case of deficient language input: creole genesis. He observed that creoles have greater complexity of morphosyntax than the pidgins that precede them, and further claimed that many creoles with disparate super- and substrate languages nonetheless share certain similar features, such as having a tense–modality–aspect system with such morphemes occurring in that order. These phenomena occur despite the fact that the input data exhibit significant variability and lack models for complex structures; this environment is known as "linguistic chaos". 

He thus proposed the language bioprogram hypothesis, suggesting that these similarities and expansion of grammar can be attributed to a common "structure of a species-specific program for language, genetically coded and expressed … in the structures and modes of operation of the human brain" [@bickertonLanguageBioprogramHypothesis1984]. This hypothesis is based on his claims that several of these shared grammatical features have no antecedent in the pidgin, or the superstrate or substrate languages. Bickerton further claimed that "the effectiveness of transmission of pre-existing languages will vary inversely with the degree to which bioprogram features are able to emerge" [@bickertonLanguageBioprogramHypothesis1984], proposing a "pidginization index" that varies according to shifts in the proportion between slave and master populations, such that a creole with a lower index has had less influence of the superstrate and thus reflects more characteristics of the bioprogram. 

Bickerton proposed that the language bioprogram hypothesis suggests that "the infrastructure of language is specified at least as narrowly as Chomsky has claimed" [@bickertonLanguageBioprogramHypothesis1984], referring to the innate specification of UG. More specifically, he employs Chomsky's theory that UG can be defined as a set of parameters each specifying an aspect of grammar, with each parameter having a small number of possible settings such that the possible combinations of these settings give rise to the possible core grammars of human language. Then, "the bioprogram grammar would simply constitute the list of preferred settings that the child, in the absence of contrary evidence, would assume to be appropriate" [@bickertonLanguageBioprogramHypothesis1984]. That is, the bioprogram reflects the unmarked values of the various parameters, and can be understood as a more specified theory about $S_0$.

Subsequent scholars have pointed out that creole genesis and language acquisition occur under different conditions, and thus there is no *a priori* reason to assume that these distinct linguistic environments should relate to the same processes and principles [e.g., @baptistaUniversalGrammarBioprogram2012]. Furthermore, the school of emergentism counter-proposed that universal language properties may simply arise from domain-general abilities such as statistical learning and attention, in conjunction with the constraints on human communication frameworks, such as oral and aural physiology, neurophysiology, and social networks, without requiring any innate or specialist module [e.g., @batesInnatenessEmergentism1998]. Nonetheless, these ideas reflect a growing interest in the language acquisition and development process, and more specific characterisation of what exactly constitutes "language" as a human capability.

## The evolution of generativism

Chomsky's generativism underwent significant change over the course of the late twentieth century. His initial formulations of transformational grammar relied on specific phrase structure rules and transformations [@chomskySyntacticStructures1957], but later revisions introduced more abstractions, including the replacement of individual phrase structure rules with X-bar theory, and specific transformations with more general constraints and rules. This generalisation culminated in Government and Binding Theory (GBT) [@chomskyLecturesGovernmentBinding1981; @chomskyConceptsConsequencesTheory1982], which involves grammatical modules that govern separate aspects of grammaticality. Since the 1990s, Chomsky has turned his focus towards the Minimalist Program (MP) [@chomskyMinimalistProgramLinguistic1993], which seeks to approach syntax from the "bottom-up" based on the conceptual guideline of "perfection"---i.e., what an optimal theory of I-language *should* look like. Practically, many contemporary Chomskyan generativists still adopt an approach similar to that of GBT, while the MP often focuses on high-level theoretical issues due to its somewhat more austere characterisation of grammar. Chomsky admits that, under the latter paradigm, "virtually every aspect of (I-)language remains a problem" [@chomskyGenerativeGrammarFaculty2019], and generativists thus continue endeavouring to reconcile their toolkit with the available empirical evidence.

## Conclusion

The generativist project brought important scrutiny to the object of linguistic study, and provided a systematic and robust framework for analysing syntax. The generativists' focus on UG in particular introduced novel conceptions on the nature of language and the tools used to study and describe it. In this regard, Chomsky's ideas have been revolutionary in the field of linguistics [@newmeyerHasThereBeen1986], to the extent that alternative theories often reference his work as a point of departure [@wasowGenerativeGrammarRule2017], and linguistics today continues to be influenced by his ideas regarding competence, nativism, and universality.
