# Universals and variation

## Introduction

The school of generativism adopted a largely rationalist approach to language, basing its concepts and theories on arguments from reason (e.g., the poverty of the stimulus argument leading to the positing of an innate language acquisition device). On the other hand, other fields of linguistic inquiry in the mid-twentieth century adopted a more empiricist approach, focusing on generalisations and conclusions drawn from observed data [@markieRationalismVsEmpiricism2023]. Two such fields that emerged during this period are typology and (variationist) sociolinguistics, and their contributions to linguistics can be understood in terms of how they handled the related concepts of universals and variation.

## Typology: Characterising cross-linguistic variation

Chomsky's conception of generativism meant that it is possible to understand universal grammar through studying a single language, and perhaps even a single speaker, since its role is to account for language capability that cannot be explained developmentally by primary linguistic data. On the other hand, typology is fundamentally cross-linguistic and comparative, and attempts to characterise and describe the variation among different languages [@croftTypologyUniversals2017]. Furthermore, while the relativistic view proposed by the American structuralists suggested that languages can vary arbitrarily and without limit [@joosReadingsLinguisticsDevelopment1957], typology was interesting in studying the constraints on such variation through the systematic analysis of a wide variety of languages.

The typological approach has been a component of comparative linguistics since the latter's emergence; a prominent example is morphological typology (isolating, fusional, agglutinative), first articulated by @schlegelUberSpracheUnd1808. However, the founder of modern typology is often considered to be Joseph Greenberg, who in 1963 published his now-classic article on the typology of word order [@greenbergUniversalsGrammarParticular1963]. In this work, Greenberg surveyed 30 languages over many families and geographical areas, including language isolates such as Basque and Burushaski. He then analysed correlations across combinations of features in different languages, and thereby described implicational universals (i.e., of the form "given *x*, we find *y"*) regarding the order of sets of elements such as subject--verb--object, adjective--noun, and adposition--noun.

Furthermore, Greenberg attempted to explain the nature of such universals by proposing two competing motivations. The first is dominance, which refers to a preference for one order over the other. For example, the verb--object order is dominant over the object--verb order. The second is harmony, which refers to a dependency between particular orders. For example, the adjective--noun order is harmonic with the numeral--noun order. The tension between these two principles can be described as follows: the dominant order can always occur, but the recessive (i.e., non-dominant) order can only occur when a harmonic construction is also present.

Considering different facets of word order, Greenberg identified three main types of languages. Type I has a verb--subject--object order, along with noun--adjective and prepositions. Type II has a subject--verb--object order, along with noun--adjective and prepositions. Type III has a subject--object--verb order, along with adjective--noun and postpositions. The existence of Types I and III demonstrate harmony, while Type II can be explained by the general dominance of noun--adjective. These motivations thus explain why these types are much more common than other possible orderings (e.g., object--subject--verb).

Greenberg's revolution of typology can be characterised by three key contributions [@whaleyIntroductionTypologyUnity1997]. Firstly, Greenberg focused on structures within languages, rather than features of the language "as a whole". This allowed for more fine-grained analyses that were nuanced, rather than discrete but inaccurate categorisations of languages. This in turn meant that Greenberg could make use of systematic quantitative and qualitative methods to study typology, rather than vague and often subjective descriptions and characterisations. Finally, Greenberg's study of a diversity of languages emphasised the importance of eliminating potential genetic or areal biases in the language data when determining typological tendencies cross-linguistically. These principles have informed subsequent typological work, improving the precision of empirical descriptions and the validity of extracted generalisations.

## The contribution of typology

The field of typology has demonstrated an approach that employs both statistical tendencies and logical deduction to describe implicational universals, in opposition to the Chomskyan absolute universals, which by their nature are exceptionless and somewhat more theoretical (since they must be indirectly derived from assertions about language acquisition). Additionally, while Chomskyan universals have their origin in a posited biological language acquisition device, typological universals typically depend on functional explanations (e.g., the principle of economy), thereby relating patterns in variation to underlying cognitive principles and the organisation of knowledge and experience.

Typological work has also been used to support other schools and theories, including generativism itself. One example is Jakobson's later investigation into child language acquisition, in which he claimed that the chronological order of children's acquisition of phonemes aligns with orders of precedence observed in the languages of the world [@jakobsonChildLanguageAphasia1968]. For example, children learn to pronounce stops before fricatives, and similarly, languages that contain fricatives also contain stops. Another example is Keenan and Comrie's study of relative clauses, in which they propose the noun phrase accessibility hierarchy (purported to be a component of universal grammar) based on the types of relative clause constructions that occur across various languages [@keenanNounPhraseAccessibility1977]. In general implicational and absolute universals can be unified by proposing an underlying hierarchy that holds across languages, such that extant variation must nonetheless conform to the hierarchy.

In a more anthropological dimension, Berlin and Kay conducted a typological study of basic colour terms in 98 languages, finding that there were universal restrictions on the sets of colour terms that can exist in a language, as colour terms were acquired in an ordered, stage-like manner [@berlinBasicColorTerms1969]. This has inspired much subsequent work on whether colour processing (e.g., perception, memory) is affected by colour terms and categories, thereby contributing to evidence regarding the Whorfian hypothesis [@davidoffColourCategoriesStoneage1999; @kayLanguageThoughtColor2006; @kayWorldColorSurvey2010]. The researchers also claim that this hierarchy reflects a cultural evolutionary process, in which languages' systems of colour terms develop over time, thereby connecting the synchrony of implicational universals with the diachrony of language change.

In general, typology has demonstrated that variation across languages can be studied systematically, rather than being arbitrary and unconstrained. It is also interesting to note that many implicational universals have been observed and described, while the set of accepted absolute universals remains relatively small (or indeed nonexistent) [@croftTypologyUniversals2017]. This may prompt a rethinking of the notion of "language universals", and indeed the conception of "universal grammar" itself.

## Variationism: Characterising intra-linguistic variation

Another aspect of the generativist project is its rejection of language use as an object of study, in favour of the structural essence of the language. This can be seen in Chomsky's distinction between I-language and E-language, or between competence and performance, and has its roots in the Saussurean *langue* vs *parole*. The Chomskyan notion of I-language also meant that investigations into the structure of language are necessarily individual---no two humans share the same I-language, and the differences between particular I-languages are due to idiosyncrasies in the primary linguistic data received during the language acquisition period. (In practice, many generativists characterise "language" as being sufficiently similar across individuals within the same speech community to permit coherent study [@chomskyInterviewLinguisticVariation2015].) Contrastingly, the variationist school focused on language in terms of its social communicative function, and suggested that variation in language is systematic and analysable (rather than chaotic and random), drawing from earlier work in dialectology and sociology.

Early ideas regarding sociolinguistics arose around the turn of the twentieth century, such as in the work of @gauchatLunitePhonetiqueDans1905. Nonetheless, modern sociolinguistics only became established through the work of William Labov, beginning with his seminal study in Martha's Vineyard, an island in Massachusetts [@labovSocialMotivationSound1963]. In this work, he introduced the notion of the linguistic variable, which is a feature of language that varies across speakers. When such variables are frequent, stratified, and salient, but immune from conscious distortion, they serve as a useful source to investigate sociolinguistic variation. In particular, the Martha's Vineyard study found that islanders' resistance to the ways of the mainland was reflected in the preservation of variables that were more archaic, on the basis of data related to islanders' social position, opinions, and linguistic production.

Labov's study demonstrated that variation among speakers was neither random nor free; instead, the distribution of variants was systematic and constrained by social factors. Furthermore, he proposed that synchronic variation could be seen as a snapshot of diachronic change, thereby suggesting that language change is observable. Subsequent work by Labov further refined the methodology for sociolinguistic data collection: for example, varying the topic and style of an interview could elicit different registers within the same speaker [@labovSocialStratificationEnglish1966], and the pressures related to an interview setting could also be reduced by conducting group interviews (with family or peers) [@labovStudyNonstandardEnglish1968], or by adopting elicitation techniques without explicit observation [@labovSocialStratificationNew1972]. These studies helped to clarify the role of context in sociolinguistic variation, and also provided useful techniques to minimise such effects when studying other sociological variables.

## The contribution of variationism

The pioneering work of Labov and other sociolinguistics scholars demonstrated that language variation is structured and orderly, and reflects inherent variability in a grammatical system rather than randomness [@weinrichEmpiricalFoundationsTheory1968]. This opposed contemporary views that attempted to eliminate real-world variability in order to study the abstract object of language. The import of methodological approaches from other social sciences also helped to provide this field with quantitative tools to analyse empirical data probabilistically and in detail, while generativism tended to be more theoretical, deterministic, and general.

Variationism also contributed ideas relating to the field of historical linguistics. The study of age-graded variation has led to ideas such as the apparent-time hypothesis, which suggests that language change can be studied by comparing the language use of speakers of different ages, under the assumption that differences among different generations of speakers reflect diachronic developments in the language [@baileyRealApparentTime2002]. Variationist sociolinguistics has also been used to support the wave--diffusion model of language change [@trudgillLinguisticChangeDiffusion1974]. Effectively, the notion that variation and change are two sides of the same coin promoted the reintegration of synchrony and diachrony, and provided a new methodology for the study of language change as it is occurring.

Another finding of variationism is that language variation is normal and universal. As a result, variationists have also been strong proponents for correcting stereotypical beliefs about stigmatised dialects [@charityLinguistsAgentsSocial2008]. Labov's own work was also motivated by an attempt to dispel incorrect notions about African-American Vernacular English, demonstrating that this dialect is indeed structured and rule-governed, rather than being a deficient form of English [@labovStudyNonstandardEnglish1968; @labovAcademicIgnoranceBlack1972]. This perspective has prompted changes in language education pedagogy [@charity-hudleyWeLanguageEnglish2013] and has helped to shape the conversation around language abilities, particularly with regard to standard languages [@reaserDialectsSchoolEducating2017].

## Conclusion

The middle to late twentieth century saw the rise of a multitude of approaches towards variation. For the generativists, variation was relevant only insofar as it demonstrated the range of possible I-languages that universal grammar needed to account for. However, alternative approaches considered such variation to be orderly and systematic. Typology attempted to understand cross-linguistic variation by describing the nature of such variation and the constraints that it obeyed, while variationism attempted to understand intra-linguistic variation by examining sociological factors affecting the distribution of variables among speakers and settings. The variety in perspectives has resulted in a broad range of results pertaining to language, giving a more holistic account of the unity and diversity of language.
